from __future__ import annotations

DEFAULT_SOURCES = ("biobio", "mostrador")
DEFAULT_INPUT_NAME = "noticias_dia.txt"
DEFAULT_OUTPUT_NAME = "noticias_dia_enriquecidas.txt"
DEFAULT_DICTIONARY_DIR = "diccionarios"
DEFAULT_CANDIDATES_FILE = "candidatos_diccionario.json"
DEFAULT_DICTIONARY_VERSION = "heuristic_v1"

FAMILIES = [
    "macro_fiscal",
    "mercado_financiero",
    "energia_commodities",
    "empresas_instituciones",
    "politico_regulatorio",
    "geopolitico_mercado",
    "riesgo_alerta",
    "sentimiento_positivo",
    "sentimiento_negativo",
    "ruido_social",
]

FAMILY_ALIASES = {
    "macro_fiscal": "macro_fiscal",
    "fiscal": "macro_fiscal",
    "hacienda": "macro_fiscal",
    "presupuesto": "macro_fiscal",

    "mercado_financiero": "mercado_financiero",
    "mercado": "mercado_financiero",
    "financial": "mercado_financiero",
    "financial_strict": "mercado_financiero",
    "bolsa": "mercado_financiero",

    "energia_commodities": "energia_commodities",
    "energia": "energia_commodities",
    "commodities": "energia_commodities",
    "commodity": "energia_commodities",
    "petroleo": "energia_commodities",
    "petróleo": "energia_commodities",

    "empresas_instituciones": "empresas_instituciones",
    "empresas": "empresas_instituciones",
    "instituciones": "empresas_instituciones",
    "companies": "empresas_instituciones",
    "company": "empresas_instituciones",

    "politico_regulatorio": "politico_regulatorio",
    "political": "politico_regulatorio",
    "political_risk": "politico_regulatorio",
    "regulatorio": "politico_regulatorio",
    "regulacion": "politico_regulatorio",
    "regulación": "politico_regulatorio",

    "geopolitico_mercado": "geopolitico_mercado",
    "geopolitico": "geopolitico_mercado",
    "geopolítico": "geopolitico_mercado",
    "geopolitical": "geopolitico_mercado",
    "geopolitical_market": "geopolitico_mercado",

    "riesgo_alerta": "riesgo_alerta",
    "riesgo": "riesgo_alerta",
    "alerta": "riesgo_alerta",
    "risk": "riesgo_alerta",

    "sentimiento_positivo": "sentimiento_positivo",
    "positivo": "sentimiento_positivo",
    "positive": "sentimiento_positivo",

    "sentimiento_negativo": "sentimiento_negativo",
    "negativo": "sentimiento_negativo",
    "negative": "sentimiento_negativo",

    "ruido_social": "ruido_social",
    "noise": "ruido_social",
    "social_noise": "ruido_social",
}

GENERIC_CANDIDATE_STOPWORDS = {
    "gobierno", "presidente", "ministro", "autoridades", "sector", "público", "pública",
    "millones", "mil", "trabajo", "seguridad", "investigación", "salud", "ministerio",
    "desarrollo", "social", "sociales", "casos", "casa", "grupo", "relación", "datos",
    "alto", "alta", "falta", "jefe", "local", "regional", "comuna", "servicio",
    "servicios", "personas", "persona", "hechos", "inicio", "causa", "cargo", "plan",
    "resultados", "problemas", "jornada", "equipo", "ciudad", "tribunal", "informe",
    "gestión", "organización", "defensa", "justicia", "declaraciones", "partido",
}

PHRASE_NORMALIZATIONS = {
    "ee.uu.": "estados_unidos",
    "eeuu": "estados_unidos",
    "estados unidos": "estados_unidos",
    "donald trump": "donald_trump",
    "josé antonio kast": "jose_antonio_kast",
    "jose antonio kast": "jose_antonio_kast",
    "banco central": "banco_central",
    "ministerio de hacienda": "ministerio_de_hacienda",
    "ministro de hacienda": "ministro_de_hacienda",
    "tipo de cambio": "tipo_de_cambio",
    "tasa de interés": "tasa_de_interes",
    "tasa de interes": "tasa_de_interes",
    "renta fija": "renta_fija",
    "renta variable": "renta_variable",
    "wall street": "wall_street",
    "estrecho de ormuz": "estrecho_de_ormuz",
    "política fiscal": "politica_fiscal",
    "politica fiscal": "politica_fiscal",
    "déficit fiscal": "deficit_fiscal",
    "deficit fiscal": "deficit_fiscal",
    "gasto fiscal": "gasto_fiscal",
    "subsidio eléctrico": "subsidio_electrico",
    "subsidio electrico": "subsidio_electrico",
}

DEFAULT_SEED_TERMS = {
    "macro_fiscal": {
        "hacienda": 2.0,
        "ministerio_de_hacienda": 2.5,
        "presupuesto": 2.0,
        "deficit_fiscal": 2.5,
        "gasto_fiscal": 2.0,
        "politica_fiscal": 2.0,
        "subsidio": 1.3,
        "subsidio_electrico": 2.0,
        "impuestos": 2.0,
        "reforma tributaria": 2.5,
        "deuda pública": 2.0,
        "deuda publica": 2.0,
        "sueldo mínimo": 1.7,
        "sueldo minimo": 1.7,
    },
    "mercado_financiero": {
        "banco_central": 3.0,
        "cmf": 2.5,
        "dólar": 2.5,
        "dolar": 2.5,
        "tipo_de_cambio": 3.0,
        "tasa_de_interes": 2.5,
        "ipc": 2.0,
        "inflación": 2.5,
        "inflacion": 2.5,
        "imacec": 2.5,
        "bolsa": 2.0,
        "wall_street": 2.5,
        "renta_fija": 2.5,
        "renta_variable": 2.5,
        "bonos": 2.0,
        "acciones": 1.5,
        "mercado_financiero": 2.5,
    },
    "energia_commodities": {
        "petróleo": 3.0,
        "petroleo": 3.0,
        "cobre": 2.8,
        "litio": 2.5,
        "gas": 1.5,
        "combustibles": 2.0,
        "bencina": 1.7,
        "diésel": 1.7,
        "diesel": 1.7,
        "electricidad": 1.8,
        "tarifas eléctricas": 2.0,
        "tarifas electricas": 2.0,
        "enap": 2.5,
        "codelco": 2.5,
        "sqm": 2.2,
        "opep": 2.5,
    },
    "empresas_instituciones": {
        "codelco": 2.5,
        "enap": 2.3,
        "sqm": 2.3,
        "cap": 1.8,
        "copec": 2.0,
        "falabella": 2.0,
        "cencosud": 2.0,
        "banco de chile": 2.0,
        "bci": 2.0,
        "itau": 2.0,
        "itaú": 2.0,
        "cmf": 2.0,
        "banco_central": 2.0,
    },
    "politico_regulatorio": {
        "proyecto de ley": 2.0,
        "proyecto_de_ley": 2.0,
        "congreso": 2.0,
        "senado": 1.8,
        "cámara": 1.8,
        "camara": 1.8,
        "regulación": 2.0,
        "regulacion": 2.0,
        "reforma": 1.7,
        "ley": 1.2,
        "gobierno": 1.0,
        "ejecutivo": 1.0,
        "hacienda": 1.5,
        "presupuesto": 1.5,
    },
    "geopolitico_mercado": {
        "irán": 2.8,
        "iran": 2.8,
        "israel": 2.0,
        "rusia": 2.5,
        "ucrania": 2.5,
        "china": 2.0,
        "estados_unidos": 1.8,
        "donald_trump": 1.8,
        "guerra": 1.2,
        "conflicto": 1.0,
        "estrecho_de_ormuz": 3.0,
        "aranceles": 2.5,
        "sanciones económicas": 2.3,
        "sanciones economicas": 2.3,
        "sanciones financieras": 2.3,
        "exportaciones": 1.5,
        "importaciones": 1.5,
        "cadena de suministro": 2.0,
    },
    "riesgo_alerta": {
        "riesgo": 1.5,
        "crisis": 2.0,
        "alerta": 1.7,
        "incertidumbre": 2.0,
        "caída": 1.8,
        "caida": 1.8,
        "desplome": 2.5,
        "recesión": 2.5,
        "recesion": 2.5,
        "conflicto": 1.5,
        "ataque": 1.5,
        "emergencia": 1.5,
        "quiebra": 2.5,
    },
    "sentimiento_positivo": {
        "crecimiento": 1.5,
        "alza": 1.2,
        "sube": 1.2,
        "recuperación": 1.5,
        "recuperacion": 1.5,
        "mejora": 1.5,
        "acuerdo": 1.2,
        "inversión": 1.4,
        "inversion": 1.4,
        "expansión": 1.5,
        "expansion": 1.5,
    },
    "sentimiento_negativo": {
        "caída": 1.5,
        "caida": 1.5,
        "baja": 1.2,
        "crisis": 1.8,
        "riesgo": 1.4,
        "incertidumbre": 1.8,
        "desaceleración": 1.8,
        "desaceleracion": 1.8,
        "pérdidas": 1.6,
        "perdidas": 1.6,
        "quiebra": 2.2,
        "déficit": 1.5,
        "deficit": 1.5,
    },
    "ruido_social": {
        "farándula": 1.5,
        "farandula": 1.5,
        "espectáculos": 1.5,
        "espectaculos": 1.5,
        "deportes": 1.5,
        "fútbol": 1.5,
        "futbol": 1.5,
        "policial": 1.0,
        "delito": 1.0,
        "detenido": 1.0,
        "música": 1.2,
        "musica": 1.2,
        "cine": 1.2,
    },
}
